#!/usr/bin/env python3
"""
Fetch Google Scholar metrics for Tanzila Rahman and regenerate
src/data/scholar.ts.

Local usage:
    pip install scholarly fake-useragent
    python scripts/scrape_scholar.py

In CI: see .github/workflows/update-scholar.yml.

NOTE: Google Scholar aggressively rate-limits cloud IPs. If the scrape
fails (captcha / 429 / network), this script logs a warning and exits 0
WITHOUT modifying scholar.ts, so the workflow does not fail noisily and
the previously-committed values are preserved.
"""
from __future__ import annotations

import datetime
import sys
import time
import traceback
from pathlib import Path

AUTHOR_ID = "7GKKBLkAAAAJ"
REPO_ROOT = Path(__file__).resolve().parents[1]
OUT_FILE = REPO_ROOT / "src" / "data" / "scholar.ts"


def _try_fetch():
    """Try to fetch the author profile. Raises on failure."""
    from scholarly import scholarly, ProxyGenerator

    # Attempt 1: direct request
    try:
        author = scholarly.search_author_id(AUTHOR_ID)
        return scholarly.fill(author, sections=["indices", "counts"])
    except Exception as e:
        print(f"[warn] direct fetch failed: {e}", file=sys.stderr)

    # Attempt 2: free proxies (often unreliable but worth one shot)
    pg = ProxyGenerator()
    if pg.FreeProxies():
        scholarly.use_proxy(pg)
        time.sleep(2)
        author = scholarly.search_author_id(AUTHOR_ID)
        return scholarly.fill(author, sections=["indices", "counts"])

    raise RuntimeError("All fetch strategies failed")


def _build_js(author) -> str:
    today = datetime.date.today()
    # Google Scholar's "since {year}" window is the last 5 calendar years
    # (current year inclusive), so "since" year = current_year - 4.
    since_year = today.year - 4

    per_year_raw = author.get("cites_per_year", {}) or {}
    per_year = sorted(
        [{"year": int(y), "count": int(c)} for y, c in per_year_raw.items()],
        key=lambda d: d["year"],
    )

    py_lines = ",\n    ".join(
        f'{{ year: {d["year"]}, count: {d["count"]} }}' for d in per_year
    )

    return f"""// Auto-generated by scripts/scrape_scholar.py
// Last updated: {today.isoformat()}
// DO NOT EDIT MANUALLY — changes will be overwritten by the GitHub Action.

import type {{ Scholar }} from "../lib/types";

export const scholar: Scholar = {{
  profileUrl:
    "https://scholar.google.com/citations?user={AUTHOR_ID}&hl=en",
  // Headline metrics
  totals: {{
    citations: {author.get('citedby', 0)},
    citationsSince: {{ year: {since_year}, value: {author.get('citedby5y', 0)} }},
    hIndex: {author.get('hindex', 0)},
    hIndexSince: {{ year: {since_year}, value: {author.get('hindex5y', 0)} }},
    i10Index: {author.get('i10index', 0)},
    i10IndexSince: {{ year: {since_year}, value: {author.get('i10index5y', 0)} }},
  }},
  // Citations per year as shown on Google Scholar
  perYear: [
    {py_lines},
  ],
}};
"""


def main() -> int:
    try:
        author = _try_fetch()
    except Exception:
        print("[warn] Scholar fetch failed — keeping existing data.", file=sys.stderr)
        traceback.print_exc()
        return 0  # soft fail

    if not author or not author.get("citedby"):
        print("[warn] Empty result — keeping existing data.", file=sys.stderr)
        return 0

    js = _build_js(author)

    if OUT_FILE.exists() and OUT_FILE.read_text(encoding="utf-8") == js:
        print("No change in Scholar data.")
        return 0

    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text(js, encoding="utf-8")
    print(
        f"Updated {OUT_FILE.relative_to(REPO_ROOT)} — "
        f"{author.get('citedby')} citations, "
        f"h-index={author.get('hindex')}, "
        f"i10={author.get('i10index')}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
